server:
  port: 8080
 
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=CST&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
 
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
